Fix the Perforce build step on Python 3 (:issue:`3493`)
